package net.lab0.azure.profile.model.definition

import kotlin.Boolean
import kotlin.String
import kotlin.collections.List
import net.lab0.azure.profile.model.definition.enumeration.AvatarSize

interface Avatar {
  val isAutoGenerated: Boolean

  val size: AvatarSize

  val timeStamp: String

  val value: List<String>
}
