package net.lab0.azure.model.definition.profile

import kotlin.Boolean
import kotlin.String
import kotlin.collections.List
import net.lab0.azure.model.definition.enumeration.profile.AvatarSize

interface Avatar {
  val isAutoGenerated: Boolean

  val size: AvatarSize

  val timeStamp: String

  val value: List<String>
}
